CREATE TABLE "REFRESH".USERINFO
( USERID INT PRIMARY KEY,
  EMAIL VARCHAR(30) NOT NULL,
  USERNAME VARCHAR(20) NOT NULL,
  PASS VARCHAR(20) NOT NULL,
  RDATE DATETIME NOT NULL,
  ICON VARCHAR(30),
  FANSNUM INT DEFAULT(0),
  FOCUSNUM INT DEFAULT(0),
  ARTNUM INT DEFAULT(0)
);
CREATE TABLE "REFRESH".BLOG
(
  ARTICLEID INT PRIMARY KEY,
  TITLE VARCHAR(30) NOT NULL,
  ACONTENT VARCHAR(30),
  AUTHORID INT NOT NULL,
  PTIME DATETIME NOT NULL,
  VIEWS INT DEFAULT(0),
  LIKES INT DEFAULT(0),
  PUBLICITY INT DEFAULT(0),
  PROPERTY INT DEFAULT(0),
  FOREIGN KEY (AUTHORID) REFERENCES "REFRESH".USERINFO(USERID)
);
CREATE TABLE "REFRESH".COMMENTS
(
  ARTICLEID INT PRIMARY KEY,
  USERID INT NOT NULL,
  CCONTENT VARCHAR(30),
  CDATE DATETIME NOT NULL,
  LIKES INT DEFAULT(0),
  DISLIKES INT DEFAULT(0),
  FOREIGN KEY (ARTICLEID) REFERENCES "REFRESH".BLOG(ARTICLEID),
  FOREIGN KEY (USERID) REFERENCES "REFRESH".USERINFO(USERID)
);
CREATE TABLE "REFRESH".TOPIC
(
  TOPICID INT PRIMARY KEY,
  USERID INT NOT NULL,
  CTIME DATETIME NOT NULL,
  FOCUSNUM INT DEFAULT(0),
  ARTNUM INT DEFAULT(0),
  VIEWS INT DEFAULT(0),
  FOREIGN KEY (USERID) REFERENCES "REFRESH".USERINFO(USERID)
);
CREATE TABLE "REFRESH".USERFOCUS
(
  FOCUSEDID INT NOT NULL,
  FOCUSID INT NOT NULL,
  FTIME DATETIME NOT NULL,
  PRIMARY KEY(FOCUSEDID,FOCUSID)
);
CREATE TABLE "REFRESH".BLOGTOPIC
(
  TOPICID INT NOT NULL,
  ARTICLEID INT NOT NULL,
  FOREIGN KEY (TOPICID) REFERENCES "REFRESH".TOPIC(TOPICID),
  FOREIGN KEY (ARTICLEID) REFERENCES "REFRESH".BLOG(ARTICLEID)
);
CREATE TABLE "REFRESH".BROWSE
(
  USERID INT NOT NULL,
  ARTICLEID INT NOT NULL,
  BTIME DATETIME NOT NULL,
  FOREIGN KEY (USERID) REFERENCES "REFRESH".USERINFO(USERID),
  FOREIGN KEY (ARTICLEID) REFERENCES "REFRESH".BLOG(ARTICLEID)
);
